language: node_js
node_js:
  - "6.10"
  - "7.9"
matrix:
  include:
    - node_js: "8.0"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    # Allow the nightly installs to fail
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  # init chrome
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Remove all non-test dependencies
  - "npm rm --save-dev connect-redis"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"

  # Install angular-cli
  - npm install -g @angular/cli
script:
  - "ng build" 
  - "ng test --single-run --no-progress --code-coverage"
  - "ng lint"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
