environment:
  matrix:
    - nodejs_version: "6.10"
    - nodejs_version: "7.6"
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm rm --save-dev connect-redis
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install -g @angular/cli
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - ng build
  - ng test --single-run --no-progress --code-coverage
  - ng lint
version: "{build}"
